[package]
name = "suborbital"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = { git = "https://github.com/MalekiRe/bevy", branch = "malek/async_ecs", default-features = false, features = [
  "bevy_state",
  "bevy_ui_render",
  "qoi",
] }
rand = { version = "0.9", default-features = false, features = ["os_rng"] }
webbrowser = { version = "1", default-features = false, features = [
  "hardened",
] }
futures-timer = "3"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
bevy = { git = "https://github.com/MalekiRe/bevy", branch = "malek/async_ecs", default-features = false, features = [
  "x11",
  "wayland",
] }

[target.'cfg(target_family = "wasm")'.dependencies]
bevy = { git = "https://github.com/MalekiRe/bevy", branch = "malek/async_ecs", default-features = false, features = [
  "webgl2",
  "bevy_winit",
] }
getrandom = { version = "^0.3", features = ["wasm_js"] }

[profile.web-release]
inherits = "release"
codegen-units = 1
lto = "fat"
opt-level = "z"
strip = "debuginfo"
panic = "abort"
